node {


        stage('Checkout') {

            git url: 'https://github.com/siwar-benrejeb/mrjeffapp.git', credentialsId:  'git-credit-ID', branch: 'master'

        }

     
 	stage('unit test') {
		dir ('notification-service') {
        sh 'mvn test'
	}
   	 }

   	 stage('integration test') {
		dir ('notification-service') {
        sh 'mvn failsafe:integration-test failsafe:verify'

        }
   	 }

        stage('Build') {
		dir ('notification-service') {		
            	sh 'mvn clean package'
		}
        }

        stage('Image') {

            dir ('notification-service') {

	      docker.build "mrjeffapp_notificationservice"

            }

        }

        stage ('Run') {

            docker.image("mrjeffapp_notificationservice").run('-p 8080:8080 --net=host --expose=8080 -t mrjeffapp_notificationservice:latest')

        }


}
