version: "3"

services:
  
  configservice:
    build: ./config-service
    volumes:
     - ./config-service:/app
    ports:
      - "8888:8888"
    expose:
     - "8888"

  eurekaservice:
    build: ./eureka-service
    volumes:
     - ./eureka-service:/app
    ports:
      - "8761:8761"
    expose:
     - "8761"

  customerservice:
    build: ./customer-service
    volumes:
     - ./customer-service:/app
    depends_on:
     - configservice
     - eurekaservice
    restart: unless-stopped
    ports:
      - "8083:8083"
    expose:
     - "8083"

  notificationservice:
    build: ./notification-service
    volumes:
     - ./notification-service:/app
    depends_on:
     - configservice
     - eurekaservice
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
     - "8080"
     
  orderservice:
    build: ./order-service
    volumes:
     - ./order-service:/app
    depends_on:
     - configservice
     - eurekaservice
    restart: unless-stopped
    ports:
      - "8081:8081"
    expose:
     - "8081"
  productservice:
    build: ./product-service
    volumes:
     - ./product-service:/app
    depends_on:
     - configservice
     - eurekaservice
    restart: unless-stopped
    ports:
      - "8084:8084"
    expose:
     - "8084"     